language: elixir
elixir:
    - 1.0.0
    - 1.0.2
otp_release:
    - 17.1
before_install:
    - epmd -daemon
script:
    - mix test --exclude distributed:true
notifications:
    recipients:
        - james@fishcakez.com

